### ISSUE TITLE
Use hourly Arduino IDE and esp8266 from git

### ISSUE THREAD

**Issue by probonopd** [adafruit/travis-ci-arduino#13]
Is it possible to use hourly Arduino IDE and esp8266 from git with this? Reason I am asking is that building using this fails, while building locally on the latest versions of the aforementioned packages succeeds.

**Comment by fede2cr** [comment]
You can use my forked repo for now, and just do a minor chance on the URL to point it to the hourly release of the Arduino IDE. It's running 1.8.2 at the moment.
https://github.com/fede2cr/travis-ci-arduino

**Comment by ladyada** [comment]
hiya i think i'd like to stay on the most recent release since hourly builds can be broken :)
