### ISSUE TITLE
Strange behaviour when installing multiple libraries

### ISSUE THREAD

**Issue by leonardoInf** [adafruit/travis-ci-arduino#44]
When you have multiple dependencies in your project, you have to install them in seperate commands, otherwise it will not work

works: 
   - arduino --install-library "Adafruit Unified Sensor"
   - arduino --install-library "Adafruit GFX Library"

doesn't work:
  - arduino --install-library "Adafruit Unified Sensor","Adafruit GFX Library"

It seems to be an issue with the script and not arduino itself, because usually a list of libraries is accepted.

**Comment by ladyada** [comment]
yeah, i dont know why it doesnt work. if you can figure it out please submit a PR :)

**Comment by informatik-mueller** [comment]
I see that TravisCI is probably the issue here. I don't think there's much you can change in this repo. I will just submit a little change in the README so new users will not be disappointed.

**Comment by leonardoInf** [comment]
I propose [this](https://github.com/adafruit/travis-ci-arduino/pull/45) (pull request)

**Comment by ladyada** [comment]
please make a PR just for this one fix, and you can propose others in separate PRs!

**Comment by leonardoInf** [comment]
agreed

ladyada <notifications@github.com> schrieb am Fr., 12. Juli 2019, 19:08:

**Comment by ladyada** [comment]
done :)
