### ISSUE TITLE
Increase Warning Level from compilation

### ISSUE THREAD

**Issue by chatelao** [adafruit/travis-ci-arduino#5]
It would be nice to see all warnings in the compilation log. Something like "compiler.warning_level=all":
# set the maximal compiler warning level

echo -n "SET BUILD PREFERENCES: "
DEPENDENCY_OUTPUT=$(arduino --pref "compiler.warning_level=all" --save-prefs 2>&1)
if [ $? -ne 0 ]; then echo -e "\xe2\x9c\x96"; else echo -e "\xe2\x9c\x93"; fi

**Comment by toddtreece** [comment]
@chatelao do you mean an option to echo stdout for all examples even if they don't fail?

**Comment by ladyada** [comment]
i think this is already done here?
https://github.com/adafruit/travis-ci-arduino/blob/master/install.sh#L67
please re-open if you can clarify :)
