### ISSUE TITLE
Sample with local library includes (#include "sample.h") fail with "multiple definition of" warning and linker error

### ISSUE THREAD

**Issue by chatelao** [adafruit/travis-ci-arduino#6]
If a sample has a local include (#include "sample.h" with "sample.cpp") the build will fail like:
https://travis-ci.org/chatelao/MiniPirate/builds/73565839

The relevant error text:
/home/travis/arduino_ide/libraries/Adafruit_Test_Library/sample.h:xxx: **multiple definition of** `yyy(char)'

Workaround:
Remove the creation of the "ln -s .../libraries" from the script

=> No clue how to solve this permanently or if this is a problem at all for the Adafruit samples (if they contain only one ".ino" file and global "#include <sample.h>" include.

**Comment by toddtreece** [comment]
@chatelao i think this related to how your lib is structured. check out one of the Adafruit libs to see how to structure your repo: https://github.com/adafruit/Adafruit_NeoPixel

the `ln -s` is required to install the repo that's being tested, so i'm closing this one.
